# Generated by Django 6.0.3 on 2026-03-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_core_alertno_is_acti_e80787_idx_core_alertn_is_acti_5bf0c1_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="core.customer",
            ),
        ),
    ]
