# Generated by Django 6.0.3 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_sale_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
