# Generated by Django 6.0.3 on 2026-03-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_sale_due_date"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="core_transa_status_288ab7_idx",
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                    ("mobanking", "Mobanking"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="core.customer",
            ),
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="status",
        ),
    ]
