# Generated by Django 6.0.3 on 2026-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_customer_manual_due_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="alert_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
