# Generated by Django 5.2.4 on 2026-04-13 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_tipperrecord_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlocksRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial (Investment/Income)"),
                            ("stock", "Stock (Addition)"),
                            ("sale", "Sale"),
                        ],
                        help_text="Type of record: financial transaction or stock inventory update",
                        max_length=20,
                    ),
                ),
                (
                    "investment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount spent on production (for investment records)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "sale_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-calculated: quantity × price (for sale records)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        blank=True,
                        choices=[("4_inch", "4 Inch"), ("6_inch", "6 Inch")],
                        help_text="Type of unit: 4 inch or 6 inch",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of units (for stock addition or sale)",
                        null=True,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per unit (for sale records)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional details or remarks"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="core_blocks_date_16aa08_idx"),
                    models.Index(
                        fields=["record_type"], name="core_blocks_record__45fefb_idx"
                    ),
                    models.Index(
                        fields=["unit_type"], name="core_blocks_unit_ty_f563c0_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="blocks_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="core.blocksrecord",
            ),
        ),
    ]
