# Generated by Django 6.0.3 on 2026-04-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_bamboorecord_transaction_bamboo_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tipper_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="core.tipperrecord",
            ),
        ),
    ]
