# Generated by Django 6.0.3 on 2026-04-17 00:00

from django.db import migrations, models


def set_existing_material_sale_payment_status_paid(apps, schema_editor):
    BlocksRecord = apps.get_model("core", "BlocksRecord")
    CementRecord = apps.get_model("core", "CementRecord")
    BambooRecord = apps.get_model("core", "BambooRecord")

    sale_value = "sale"
    sale_only_models = (BlocksRecord, CementRecord, BambooRecord)
    paid_value = "paid"

    for model in sale_only_models:
        model.objects.exclude(record_type=sale_value).update(payment_status=None)
        model.objects.filter(record_type=sale_value).update(payment_status=paid_value)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_transaction_tipper_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocksrecord",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                help_text="Payment status for sale records only",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cementrecord",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                help_text="Payment status for sale records only",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bamboorecord",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                help_text="Payment status for sale records only",
                max_length=10,
                null=True,
            ),
        ),
        migrations.RunPython(set_existing_material_sale_payment_status_paid, migrations.RunPython.noop),
    ]
