# Generated by Django 5.2.4 on 2026-04-23 01:52

import nepali_datetime
from django.db import migrations, models


def _ad_to_bs_text(value):
    if not value:
        return None
    return nepali_datetime.date.from_datetime_date(value).strftime("%Y-%m-%d")


def backfill_bs_dates(apps, schema_editor):
    model_specs = [
        ("Transaction", "date", "bs_date"),
        ("Sale", "date", "bs_date"),
        ("Sale", "due_date", "bs_due_date"),
        ("JCBRecord", "date", "bs_date"),
        ("TipperRecord", "date", "bs_date"),
        ("AlertNotification", "due_date", "bs_due_date"),
        ("CustomerPayment", "payment_date", "bs_payment_date"),
        ("BlocksRecord", "date", "bs_date"),
        ("CementRecord", "date", "bs_date"),
        ("BambooRecord", "date", "bs_date"),
    ]

    for model_name, source_field, target_field in model_specs:
        model = apps.get_model("core", model_name)
        batch = []
        for row in model.objects.all().iterator(chunk_size=500):
            setattr(row, target_field, _ad_to_bs_text(getattr(row, source_field)))
            batch.append(row)
        if batch:
            model.objects.bulk_update(batch, [target_field], batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0027_add_customer_to_material_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertnotification",
            name="bs_due_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="bamboorecord",
            name="bs_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="blocksrecord",
            name="bs_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="cementrecord",
            name="bs_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="bs_payment_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="jcbrecord",
            name="bs_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="bs_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="bs_due_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="tipperrecord",
            name="bs_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="bs_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.RunPython(backfill_bs_dates, noop_reverse),
    ]
