# Generated by Django 5.2.4 on 2026-04-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_material_sales_pending_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="bamboorecord",
            name="alert_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bamboorecord",
            name="bs_due_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="bamboorecord",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blocksrecord",
            name="alert_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blocksrecord",
            name="bs_due_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="blocksrecord",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cementrecord",
            name="alert_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cementrecord",
            name="bs_due_date",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="cementrecord",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alertnotification",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("blocks_sale", "Blocks Sale"),
                    ("cement_sale", "Cement Sale"),
                    ("bamboo_sale", "Bamboo Sale"),
                    ("transaction", "Transaction"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
    ]
