# Generated by Django 5.2.4 on 2026-05-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_bamboorecord_alert_enabled_bamboorecord_bs_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jcbrecord",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jcb_records",
                to="core.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="jcbrecord",
            index=models.Index(
                fields=["customer"], name="core_jcbrec_custome_d33eae_idx"
            ),
        ),
    ]
