# Generated by Django 5.2.4 on 2026-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_jcbrecord_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jcbrecord",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="jcbrecord",
            name="pending_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
